### PR TITLE
fix $ value predition on swap

### PR DESCRIPTION
**Pull request by esyeng**

### CODE REVIEW

**Comment by ElianaTroper** [comment]
Changes look good, testing now...

**Comment by ElianaTroper** [comment]
If I make changes via the right box, the value is not correct:

image

**Comment by ElianaTroper** [comment]
Looks much better - is there a reason the values are different on the opposite sides?

image

**Comment by esyeng** [comment]
> Looks much better - is there a reason the values are different on the opposite sides?
> 
> image

I think that's due to the price of gard being stored somewhere as $0.99, one side is directly converting the input to dollars and the other is multiplying by 0.99

**Comment by mccabe-david** [comment]
Looks much better! There's just this line which isn't centered between the "Privacy Policy" and the "Terms & Conditions"
image

**Pull request merged**
