### PR TITLE
Adding testnet/mainnet switch

### PR DESCRIPTION
**Pull request by minhle10**
- Removed VERSION from globals.js
- VERSION stored and pulled from local storage to be used in js files.
- Created NetToggle.jsx component. This is the actual switch that is placed in the top bar.
- Topbar buttons rearrange to look better
 i. e. moved Algo price to the left. Rearranged the order of the wallet address and dark toggle button to accommodate for the addition of test/main net toggle

### CODE REVIEW

**Comment by minhle10** [comment]
Rearranged the order of the buttons on the top bar. Display of wallet address is filled solid and un-clickable. Fixed loading of CDPs on net toggling in Manage CDP's page

**Comment by ElianaTroper** [comment]
Getting a bug on attempting to launch @minhle10 

image

**Comment by minhle10** [comment]
> Getting a bug on attempting to launch @minhle10
> 
> image

I think this bug is happening because we merged main into the PR - I deleted VERSION from globals.js and when we merged main into this PR it added the " import VERSION from globals.js" back in.

**Comment by ElianaTroper** [comment]
Could you update it and make sure there are no other adverse changes from
merging in main? Lmk when I should rereview.

**Comment by minhle10** [comment]
I think it should be all set, just took out VERSION from the cdp.js imports in my lastest commit.

**Comment by minhle10** [comment]
Made the requested changes in the last commits I just made, should be ready for review now!

**Comment by ElianaTroper** [comment]
Closing, going to keep the branch but we'll come back to this if we decide we need it

**Pull request closed without merging**
