### PR TITLE
GP-559: Move quick actions above the metrics on the home page

### PR DESCRIPTION
**Pull request by minhle10**
- Made "DeFi Expert the default"
- Moved quick actions above the metrics

### CODE REVIEW

**Comment by minhle10** [comment]
Made changes talked about in meeting with Rylie (details on jira)
On Mobile: 
- Added Page name and refresh icon to the top nav bar
- Remove disconnect button on all pages except account page
- Remove white space at the top
- Display only the first four metrics, and add a button to expand the rest of the details
- Make defi expert the default and move switch below details
- Make quick access buttons uniform size and arrange them into 2 rows (3 up top 2 at the bottom)
- Fix banner width
- Fix tooltip underline so that it underlines the words

**Review by ElianaTroper — COMMENTED** [review]
Code looks good - testing on my phone now and will merge if that looks good

**Comment by ElianaTroper** [comment]
So the code looks fine, but when on desktop the font is much less readable (also occurs on the stake + swap page)

old
image

new 
image

---

The desktop version now defaults to "Help Me Out" instead of Defi expert - we want it to do Defi expert by default still. Could you revert that?

---

On desktop the old header for defi expert looked better:

old
image

new
image

---

There's no longer a disconnect wallet button on either mobile or desktop - is that intentional?

---

On desktop the page name is covered by the sidebar
image

---

Once these issues are fixed or identified as intentional we can merge

**Comment by minhle10** [comment]
- Disconnect wallet not being their was unintentional (fixed in one of the commits above)
- Made defi expert default on desktop as well. (fixed in the other commit above)

**Comment by minhle10** [comment]
Added back in previous media queries to fix drawer and page title overlap. It works on my desktop but I think it would be a good idea to have a second round of testing on a different device just to make sure.

**Comment by minhle10** [comment]
I changed the underlining because it looked like the following for a few items on desktop and mobile.
Desktop:
Screen Shot 2023-01-17 at 11 11 36 PM
Mobile:
IMG_BE2BC3B92785-1

I think it looks ok on safari and chrome, but we can revert this change if we think it would be better using the old underline.
Safari desktop:
Screen Shot 2023-01-17 at 11 15 01 PM
Safari mobile: 
IMG_3A22C4BD157E-1
Chrome desktop:
Screen Shot 2023-01-17 at 11 17 07 PM

**Comment by ElianaTroper** [comment]
Page title is still overlapped on desktop for me:

image

I'm using chrome on desktop and IMO the new underlining makes readability a lot worse:

image

**Comment by ElianaTroper** [comment]
Looks good

**Pull request merged**
