### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by ElianaTroper**
Redeployed the system, added the following txns too:
- stake (tested)
- unstake (not yet tested, no gui spot)

@esyeng can you add the loading screen to the staking page? It should be properly hooked to the stake button now.

### CODE REVIEW

**Comment by mccabe-david** [comment]
Waiting for conflict resolution before review

**Comment by ElianaTroper** [comment]
Conflict is resolved @mccabe-david 

Still work to be done (need to test unstaking, no confirmation pop up appears), but I would suggest merging this in before it gets too stale

**Comment by mccabe-david** [comment]
Staking appears to be working, although no revenue is accruing.

**Comment by mccabe-david** [comment]
You can only stake whole GARD, but besides that everything looks solid! Merging.

**Pull request merged**
