### PR TITLE
Govern page

### PR DESCRIPTION
**Pull request by minhle10**
Initial pass at Govern Page.

### CODE REVIEW

**Comment by ElianaTroper** [comment]
Can you do the following before merging:

- Resolve conflicts
- Add a link for the "Learn More on ALGO Site"
- Add tooltips to items with a tooltip, or remove them

Looks really good though

**Comment by minhle10** [comment]
resolved conflict and implemented requested changes!

**Comment by ElianaTroper** [comment]
@minhle10 can you resolve conflicts, looks good otherwise

**Comment by mccabe-david** [comment]
Govern Page looks good. For some reason, when loading the actions page it goes completely blank for me. Merging.

**Pull request merged**
