### PR TITLE
Mobile optimizations - 1st pass

### PR DESCRIPTION
**Pull request by esyeng**
Adjusts global styling rules on Drawer Navigation, mobile responsiveness on Home & Swap
edit(11/7): added stake, govern, account, borrow

### CODE REVIEW

**Comment by mccabe-david** [comment]
Absolutely love the mobile view Home & Swap! Is there any way to leave the Topbar untouched on desktop/ larger views? (I.E. wallet name, disconnect wallet, etc.) Awesome job thusfar! Users will love!

**Comment by esyeng** [comment]
> Absolutely love the mobile view Home & Swap! Is there any way to leave the Topbar untouched on desktop/ larger views? (I.E. wallet name, disconnect wallet, etc.) Awesome job thusfar! Users will love!

thanks! just pushed a commit to revert the top bar width on bigger screens

**Comment by mccabe-david** [comment]
Massive mobile improvements! Govern page (i.e. algorand positions) and borrows tab on account page both have their right sides cutoff it seems. This PR def does more good than harm but fixing those things would make it perfect imo

**Comment by mccabe-david** [comment]
Definitely looking better! I still can't seem to scroll left/right when I view through a mobile screen with chrome console. So, some tables may still be cut off.

**Comment by mccabe-david** [comment]
The new color scheme for the borrow page seems to be bleeding over to desktop. Any chance you can revert the text color? 
image

**Comment by esyeng** [comment]
> The new color scheme for the borrow page seems to be bleeding over to desktop. Any chance you can revert the text color? image

It's not bleeding over, I left it that way. Eliana seemed to like it, I wanna hear other feedback before reverting

**Comment by esyeng** [comment]
> Definitely looking better! I still can't seem to scroll left/right when I view through a mobile screen with chrome console. So, some tables may still be cut off.

which page? the only tables that don't scroll are ones that either fit entirely or are shrunk to view (transaction history for instance) - all table data should be viewable

**Comment by mccabe-david** [comment]
> > Definitely looking better! I still can't seem to scroll left/right when I view through a mobile screen with chrome console. So, some tables may still be cut off.
> 
> which page? the only tables that don't scroll are ones that either fit entirely or are shrunk to view (transaction history for instance) - all table data should be viewable

image
It's the govern page table and the borrows tab

**Comment by mccabe-david** [comment]
This will due splendid for a first pass! Noticing some text overlap on borrow page now between "your positions" & "governance rewards" for desktop btw. Strong work! Merging.

**Review by mccabe-david — APPROVED** [review]

**Pull request merged**
